name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish Apricot.WebAssembly/Apricot.csproj -c Release
    - name: Add .nojekyll file
      run: touch Apricot.WebAssembly/bin/Release/net6.0/publish/wwwroot/.nojekyll
    - name: GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: Apricot.WebAssembly/bin/Release/net5.0/publish/wwwroot
        BRANCH: gh-pages
